#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    def mcm(x, y):
        return x * y // math.gcd(x, y)

    l = a[0]
    for n in a[1:]:
        l = mcm(l, n)

    g = b[0]
    for n in b[1:]:
        g = math.gcd(g, n)

    contador = 0
    x = l
    while x <= g:
        if g % x == 0:
            contador += 1
        x += l
    return contador

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()